# docker compose file f端r die Erzeugung eines Wordpress-Servers
# -------------------------------------------------------------
# 
# baut zwei Container auf f端r Wordpress und f端r MariaDB
services:

  # der Datenbank-Server
  db:
    image: mariadb:10.2
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=superpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wpnet

  # der WEB-Server
  wordpress:
    image: wordpress:latest
    ports:
      - 8001:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wpnet

# Volume f端r die Datenbank
volumes:
  db_data:

# eigenes Netzwerk
networks:
  wpnet:
    driver: bridge

